version: "3"
services:
  nginx:
    image: nginx:mainline
    container_name: diomedes_nginx
    volumes:
      - $PWD/conf.d:/etc/nginx/conf.d
      - .:/app
      - ./static:/app/static
      - "/etc/localtime:/etc/localtime:ro"
      - $PWD/certbot/conf:/etc/letsencrypt
      - $PWD/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - dioapp
    links:
      - "dioapp:dioapp"
    
  certbot:
    image: certbot/certbot
    volumes:
      - $PWD/certbot/conf:/etc/letsencrypt
      - $PWD/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  dioredis:
    image: redis:4-alpine
    # Change "defaultpass" to a more secure password
    command: redis-server --requirepass defaultpass
    ports:
      - "6379:6379"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - ./data:/data

  dioapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: diomedes
    container_name: diomedes_web
    links:
      - "dioredis:dioredis"
    depends_on:
      - dioredis
      - dioscheduler
      - dioworker
    volumes:
      - .:/app
      - ./static:/app/static
      - "/etc/localtime:/etc/localtime:ro"
    env_file:
      - ./.env
    ports:
      - "8000:8000"

  dioscheduler:
    image: diomedes
    container_name: diomedes_rqscheduler
    command: python3 manage.py jobs
    volumes:
      - .:/app
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - dioredis
    links:
     - "dioredis:dioredis"

  dioworker:
    image: diomedes
    container_name: diomedes_rqworker
    command: python3 manage.py rqworker
    volumes:
      - .:/app
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - dioredis
    links:
    - "dioredis:dioredis"
