version: "3"
services:
  nginx:
    image: nginx:mainline
    container_name: diomedes_nginx
    volumes:
      - $PWD/conf.d-dev:/etc/nginx/conf.d
      - ./static:/app/static
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "80:80"
    depends_on:
      - dioapp
    links:
      - "dioapp:dioapp"

  dioredis:
    image: redis:4-alpine
    ports:
      - "6379:6379"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - ./data:/data

  dioapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: diomedes
    container_name: diomedes_web
    links:
      - "dioredis:dioredis"
      - "diodb:diodb"
    depends_on:
      - dioredis
      - diodb
    volumes:
      - .:/app
      - "/etc/localtime:/etc/localtime:ro"
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=diomedes.settings.local
  
  diocelery:
    image: diomedes
    container_name: diomedes_celery_b
    command: ['celery', '-A', 'diomedes', 'worker','-B', '-l', 'info']
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - .:/app
    depends_on:
      - dioredis
      - diodb
    links:
     - "dioredis:dioredis"
     - "diodb:diodb"
  
  diodb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: