# Generated by Django 2.1.4 on 2018-12-28 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254)),
                ('movie_name', models.CharField(max_length=20)),
                ('movie_language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Tamil', 'Tamil'), ('Punjabi', 'Punjabi'), ('Telugu', 'Telugu'), ('Kannada', 'Kannada'), ('Malayalam', 'Malayalam')], default='Hindi', max_length=20)),
                ('movie_dimension', models.CharField(choices=[('2D', '2D'), ('2D 4DX', '2D 4DX'), ('3D', '3D'), ('3D 4DX', '3D4X'), ('IMAX 3D', 'IMAX 3D')], default='2D', max_length=20)),
                ('movie_date', models.DateField()),
                ('movie_found', models.BooleanField(default=False)),
                ('task_completed', models.BooleanField(default=False)),
                ('notified', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviealert.Region', to_field='code')),
            ],
        ),
    ]
