# Generated by Django 2.1.7 on 2019-08-11 16:00

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('moviealert', '0001_initial'), ('moviealert', '0002_auto_20190427_2304'), ('moviealert', '0003_auto_20190428_0115'), ('moviealert', '0004_auto_20190429_2232'), ('moviealert', '0005_auto_20190808_2003'), ('moviealert', '0006_auto_20190809_0048'), ('moviealert', '0007_auto_20190809_0051'), ('moviealert', '0008_auto_20190811_1506'), ('moviealert', '0009_auto_20190811_1532')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200)),
                ('movie_language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Tamil', 'Tamil'), ('Punjabi', 'Punjabi'), ('Telugu', 'Telugu'), ('Kannada', 'Kannada'), ('Malayalam', 'Malayalam')], default='Hindi', max_length=20)),
                ('movie_dimension', models.CharField(choices=[('2D', '2D'), ('2D 4DX', '2D 4DX'), ('3D', '3D'), ('3D 4DX', '3D 4DX'), ('IMAX 2D', 'IMAX 2D'), ('IMAX 3D', 'IMAX 3D')], default='2D', max_length=20)),
                ('movie_date', models.DateField()),
                ('task_completed', models.BooleanField(default=False)),
                ('search_count', models.IntegerField(default=0)),
                ('dropped', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviealert.Region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Tamil', 'Tamil'), ('Punjabi', 'Punjabi'), ('Telugu', 'Telugu'), ('Kannada', 'Kannada'), ('Malayalam', 'Malayalam')], default='Hindi', max_length=20)),
                ('dimension', models.CharField(choices=[('2D', '2D'), ('2D 4DX', '2D 4DX'), ('3D', '3D'), ('3D 4DX', '3D 4DX'), ('IMAX 2D', 'IMAX 2D'), ('IMAX 3D', 'IMAX 3D')], default='2D', max_length=20)),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('dropped', models.BooleanField(default=False)),
                ('found_time', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subregion_code', models.CharField(blank=True, max_length=20, null=True)),
                ('subregion_name', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviealert.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('subregion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviealert.SubRegion')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subregion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moviealert.SubRegion')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moviealert.Region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TheaterLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found', models.BooleanField(default=False)),
                ('found_at', models.DateTimeField()),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviealert.Reminder')),
            ],
        ),
        migrations.RenameField(
            model_name='subregion',
            old_name='subregion_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='subregion',
            old_name='subregion_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='theater',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moviealert.Region'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='subregion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moviealert.SubRegion'),
        ),
        migrations.AddField(
            model_name='theaterlink',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviealert.Theater'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='theaters',
            field=models.ManyToManyField(related_name='reminders', through='moviealert.TheaterLink', to='moviealert.Theater'),
        ),
        migrations.AlterField(
            model_name='theaterlink',
            name='found_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
