# Generated by Django 2.1.7 on 2019-03-05 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('moviealert', '0001_initial'), ('moviealert', '0002_cinemas_subregion'), ('moviealert', '0003_auto_20190101_2148'), ('moviealert', '0004_auto_20190223_0043'), ('moviealert', '0005_auto_20190223_2102'), ('moviealert', '0006_auto_20190225_2204'), ('moviealert', '0007_auto_20190306_0141')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254)),
                ('movie_name', models.CharField(max_length=200)),
                ('movie_language', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Tamil', 'Tamil'), ('Punjabi', 'Punjabi'), ('Telugu', 'Telugu'), ('Kannada', 'Kannada'), ('Malayalam', 'Malayalam')], default='Hindi', max_length=20)),
                ('movie_dimension', models.CharField(choices=[('2D', '2D'), ('2D 4DX', '2D 4DX'), ('3D', '3D'), ('3D 4DX', '3D4X'), ('IMAX 3D', 'IMAX 3D')], default='2D', max_length=20)),
                ('movie_date', models.DateField()),
                ('task_completed', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviealert.Region')),
                ('dropped', models.BooleanField(default=False)),
                ('search_count', models.IntegerField(default=0)),
            ],
        ),
    ]
