# Generated by Django 2.1.7 on 2019-04-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviealert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='movie_dimension',
            field=models.CharField(choices=[('2D', '2D'), ('2D 4DX', '2D 4DX'), ('3D', '3D'), ('3D 4DX', '3D 4DX'), ('IMAX 2D', 'IMAX 2D'), ('IMAX 3D', 'IMAX 3D')], default='2D', max_length=20),
        ),
    ]
