# Generated by Django 2.1.7 on 2019-04-29 17:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviealert', '0003_auto_20190428_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='venues',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), blank=True, null=True, size=None),
        ),
    ]
