# Generated by Django 2.1.4 on 2019-02-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviealert', '0003_auto_20190101_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dropped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='search_count',
            field=models.IntegerField(default=0),
        ),
    ]
