# Generated by Django 2.1.4 on 2019-02-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviealert', '0004_auto_20190223_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='movie_name',
            field=models.CharField(max_length=200),
        ),
    ]
