# Generated by Django 2.1.7 on 2019-08-08 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moviealert', '0004_auto_20190429_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubRegion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviealert.SubRegion')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviealert.Region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='theater',
            name='venue_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
