# Generated by Django 2.1.4 on 2019-02-25 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviealert', '0005_auto_20190223_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='movie_found',
        ),
        migrations.RemoveField(
            model_name='task',
            name='notified',
        ),
    ]
