# Generated by Django 2.1.9 on 2019-08-08 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviealert', '0005_auto_20190808_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='SubRegion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moviealert.SubRegion'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moviealert.Region'),
        ),
    ]
