# Generated by Django 2.1.7 on 2019-03-05 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviealert', '0006_auto_20190225_2204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cinemas',
        ),
        migrations.RemoveField(
            model_name='subregion',
            name='region_code',
        ),
        migrations.DeleteModel(
            name='SubRegion',
        ),
    ]
