# Generated by Django 2.1.9 on 2019-08-08 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviealert', '0006_auto_20190809_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='SubRegion',
            new_name='subregion',
        ),
    ]
