# Generated by Django 2.1.7 on 2019-08-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviealert', '0008_auto_20190811_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theaterlink',
            name='found_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
